# Minecraft Bedrock Server in a Docker Compose

# Sergei Nazarov
# sergey.va.nazarov@gmail.com
# www..com

# Install the Docker Engine by following the official guide: https://docs.docker.com/engine/install/
# Install the Docker Compose by following the official guide: https://docs.docker.com/compose/install/

# Note that plugins folder should be in the same directory with minecraft-server-docker-compose.yml

# Deploy Minecraft server with a Docker Compose using the command:
# docker-compose -f minecraft-server-docker-compose.yml -p minecraft up -d

# Minecraft Server Management

# Apply new configuration after a change in the `minecraft-server-docker-compose.yml` using the command:
# docker-compose -f minecraft-server-docker-compose.yml -p minecraft up -d

# Connect to the Minecraft server command-line interface using the command:
# docker exec -i ContainerName rcon-cli

# Stop Minecraft server using the command:
# docker exec ContainerName rcon-cli stop

volumes:
  mc-volume:
  external:
  name: mc-volume

services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    volumes:
      - mc-volume:/data
      - ./plugins:/plugins:ro
    environment:
      EULA: 'true'
      SERVER_NAME: mc-server
      # Game mode (replace with yours)
      # creative, survival, adventure, spectator (replace with yours)
      GAMEMODE: creative
      # Force gamemode (replace with yours)
      FORCE_GAMEMODE: 'false'
      # Difficulty (replace with yours)
      # peaceful, easy, normal, hard
      DIFFICULTY: normal
      ALLOW-CHEATS: 'true'
      # Max players (replace with yours)
      MAX_PLAYERS: 10
      # Online mode (replace with yours)
      ONLINE_MODE: 'true'
      WHITE_LIST: 'false'
      # View distance (replace with yours)
      VIEW_DISTANCE: 25
      TICK_DISTANCE: 4
      PLAYER_IDLE_TIMEOUT: 60
      MAX_THREADS: 2
      LEVEL_NAME:
      LEVEL_SEED:
      DEFAULT_PLAYER_PERMISSION_LEVEL: 'member'
      TEXTUREPACK_REQUIRED: 'false'
      SERVER_AUTHORITATIVE_MOVEMENT:
      PLAYER_MOVEMENT_SCORE_THRESHOLD:
      PLAYER_MOVEMENT_DISTANCE_THRESHOLD:
      PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS:
      CORRECT_PLAYER_MOVEMENT:
      # Level type and generator settings (replace with yours)
      # DEFAULT, FLAT, LEGACY
      LEVEL_TYPE: DEFAULT
      MOTD: mc-server - Welcome to Dima's Minecraft server
    ports:
      - "19132:19132"
    restart: unless-stopped

  backup:
    image: kaiede/minecraft-bedrock-backup
    name: minecraft_backup
    restart: always
    depends_on:
      - "mc-server"
    environment:
      
    volumes:
    - minecraft-data:/data:ro
    # Minecraft backups location
    - /srv/minecraft-data/backups:/backups
    #tty: 'true'
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #  - /opt/bedrock/backups:/backups
    #  - /opt/bedrock/server:/server
    network_mode: 'service:minecraft'
    restart: unless-stopped
    depends_on:
      minecraft:
        condition: service_healthy
        
    containers:
      bedrock:
       - name: mc-server
         worlds:
        - /server/worlds/MyWorld
    schedule:
      interval: 23h
    trim:
      trimDays: 2
      keepDays: 14
      minKeep: 1
